# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03dbb8011a3deb719a8c91e809f05dc30211f72b41e0c713c7e90ec44841efdd0e2d161445e8f35b1acc7f743467719e33c426b79deda06e92d38bb4cb12025

test:
  secret_key_base: 09a011a64bf3487dd9411e838e883e5b79b56c532365ce8ae93a63c86cd32043ac6af366f900ac11520d938fc0d1181bbfd0d7c112c439b01289e5cc849a0ff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

GOOGLE_API_KEY: AIzaSyCG5UTuXw4QMENTO-tGRG2Drs3ARECjdc0
